import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NavBar} from "@/app/NavBar";
import {Theme, ThemePanel} from "@radix-ui/themes";
import {AuthProvider} from "@/app/auth/Provider";
import NavbarWrapper from "@/app/components/NavbarWrapper";
import QueryClientProvider from "@/app/QueryClientProvider";


const inter = Inter({
    subsets: ['latin'],
    variable: "--font-inter",
})

export const metadata: Metadata = {
  title: 'FlowSphere',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <QueryClientProvider>
          <AuthProvider>
              <Theme appearance={'dark'} accentColor={'ruby'}>
                  <NavbarWrapper/>
                  <main>
                      {children}
                  </main>
              </Theme>
          </AuthProvider>
      </QueryClientProvider>
      </body>
    </html>
  )
}
